import mysql from 'mysql2/promise';
import { exec } from 'child_process';
import { promisify } from 'util';
import fs from 'fs';
import path from 'path';
import { BaseAdapter } from './BaseAdapter.js';

const execAsync = promisify(exec);

export class MysqlAdapter extends BaseAdapter {
  async testConnection() {
    const connection = await mysql.createConnection({
      host: this.config.host || '127.0.0.1',
      port: Number(this.config.port) || 3306,
      user: this.config.user || 'root',
      password: this.config.password || '',
      database: this.config.database
    });
    await connection.ping();
    await connection.end();
    return true;
  }

  async backup(options = {}) {
    const host = this.config.host || '127.0.0.1';
    const port = Number(this.config.port) || 3306;
    const user = this.config.user || 'root';
    const pass = this.config.password || '';
    const db = this.config.database;

    if (!db) {
      throw new Error('Database name is required for MySQL backup.');
    }

    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const tempDir = options.tempDir || './tmp';
    if (!fs.existsSync(tempDir)) {
      fs.mkdirSync(tempDir, { recursive: true });
    }
    const outputFile = path.join(tempDir, `mysql_${db}_${timestamp}.sql`);

    const tablesArg = options.tables ? options.tables.split(',').map(t => t.trim()).join(' ') : '';

    try {
      // Try mysqldump native CLI first
      let cmd = `mysqldump -h ${host} -P ${port} -u ${user} `;
      if (pass) {
        cmd += `-p"${pass}" `;
      }
      cmd += `${db} ${tablesArg} > "${outputFile}"`;

      await execAsync(cmd);
      return outputFile;
    } catch (err) {
      // Fallback to JS driver export if mysqldump is not available
      const connection = await mysql.createConnection({
        host, port, user, password: pass, database: db
      });

      let tablesToExport = [];
      if (options.tables) {
        tablesToExport = options.tables.split(',').map(t => t.trim());
      } else {
        const [rows] = await connection.query('SHOW TABLES');
        tablesToExport = rows.map(r => Object.values(r)[0]);
      }

      let sqlDump = `-- MySQL Dump generated by LeanNodeJsDatabaseBackupUtility\n`;
      sqlDump += `CREATE DATABASE IF NOT EXISTS \`${db}\`;\nUSE \`${db}\`;\n\n`;

      for (const table of tablesToExport) {
        const [createRows] = await connection.query(`SHOW CREATE TABLE \`${table}\``);
        if (createRows.length > 0) {
          sqlDump += `DROP TABLE IF EXISTS \`${table}\`;\n`;
          sqlDump += `${createRows[0]['Create Table']};\n\n`;
        }

        const [dataRows] = await connection.query(`SELECT * FROM \`${table}\``);
        for (const row of dataRows) {
          const keys = Object.keys(row).map(k => `\`${k}\``).join(', ');
          const values = Object.values(row).map(v => {
            if (v === null) return 'NULL';
            if (typeof v === 'number') return v;
            return `'${String(v).replace(/'/g, "''")}'`;
          }).join(', ');
          sqlDump += `INSERT INTO \`${table}\` (${keys}) VALUES (${values});\n`;
        }
        sqlDump += `\n`;
      }

      await connection.end();
      fs.writeFileSync(outputFile, sqlDump, 'utf8');
      return outputFile;
    }
  }

  async restore(options = {}) {
    const host = this.config.host || '127.0.0.1';
    const port = Number(this.config.port) || 3306;
    const user = this.config.user || 'root';
    const pass = this.config.password || '';
    const db = this.config.database;
    const file = options.file;

    if (!file || !fs.existsSync(file)) {
      throw new Error(`Restore SQL file not found: ${file}`);
    }

    try {
      let cmd = `mysql -h ${host} -P ${port} -u ${user} `;
      if (pass) {
        cmd += `-p"${pass}" `;
      }
      if (db) {
        cmd += `${db} `;
      }
      cmd += `< "${file}"`;

      await execAsync(cmd);
      return true;
    } catch (err) {
      // Driver fallback for SQL script execution
      const connection = await mysql.createConnection({
        host, port, user, password: pass, database: db, multipleStatements: true
      });

      const sql = fs.readFileSync(file, 'utf8');
      await connection.query(sql);
      await connection.end();
      return true;
    }
  }
}
