import pkg from 'pg';
const { Client } = pkg;
import { exec } from 'child_process';
import { promisify } from 'util';
import fs from 'fs';
import path from 'path';
import { BaseAdapter } from './BaseAdapter.js';

const execAsync = promisify(exec);

export class PostgresAdapter extends BaseAdapter {
  async testConnection() {
    const client = new Client({
      host: this.config.host || '127.0.0.1',
      port: Number(this.config.port) || 5432,
      user: this.config.user || 'postgres',
      password: this.config.password || '',
      database: this.config.database || 'postgres'
    });
    await client.connect();
    await client.query('SELECT 1');
    await client.end();
    return true;
  }

  async backup(options = {}) {
    const host = this.config.host || '127.0.0.1';
    const port = Number(this.config.port) || 5432;
    const user = this.config.user || 'postgres';
    const pass = this.config.password || '';
    const db = this.config.database || 'postgres';

    const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
    const tempDir = options.tempDir || './tmp';
    if (!fs.existsSync(tempDir)) {
      fs.mkdirSync(tempDir, { recursive: true });
    }
    const outputFile = path.join(tempDir, `postgres_${db}_${timestamp}.sql`);

    let tableFlags = '';
    if (options.tables) {
      tableFlags = options.tables.split(',').map(t => `-t ${t.trim()}`).join(' ');
    }

    try {
      let env = { ...process.env, PGPASSWORD: pass };
      let cmd = `pg_dump -h ${host} -p ${port} -U ${user} ${tableFlags} -d ${db} -F p -f "${outputFile}"`;

      await execAsync(cmd, { env });
      return outputFile;
    } catch (err) {
      // Driver fallback
      const client = new Client({ host, port, user, password: pass, database: db });
      await client.connect();

      let tablesToExport = [];
      if (options.tables) {
        tablesToExport = options.tables.split(',').map(t => t.trim());
      } else {
        const res = await client.query(`
          SELECT table_name 
          FROM information_schema.tables 
          WHERE table_schema='public' AND table_type='BASE TABLE'
        `);
        tablesToExport = res.rows.map(r => r.table_name);
      }

      let sqlDump = `-- PostgreSQL Dump generated by LeanNodeJsDatabaseBackupUtility\n\n`;

      for (const table of tablesToExport) {
        const colRes = await client.query(`
          SELECT column_name, data_type 
          FROM information_schema.columns 
          WHERE table_name = $1
        `, [table]);

        if (colRes.rows.length === 0) continue;

        const cols = colRes.rows.map(r => `"${r.column_name}"`).join(', ');

        const dataRes = await client.query(`SELECT * FROM "${table}"`);
        for (const row of dataRes.rows) {
          const values = Object.values(row).map(v => {
            if (v === null) return 'NULL';
            if (typeof v === 'number' || typeof v === 'boolean') return v;
            return `'${String(v).replace(/'/g, "''")}'`;
          }).join(', ');
          sqlDump += `INSERT INTO "${table}" (${cols}) VALUES (${values});\n`;
        }
      }

      await client.end();
      fs.writeFileSync(outputFile, sqlDump, 'utf8');
      return outputFile;
    }
  }

  async restore(options = {}) {
    const host = this.config.host || '127.0.0.1';
    const port = Number(this.config.port) || 5432;
    const user = this.config.user || 'postgres';
    const pass = this.config.password || '';
    const db = this.config.database || 'postgres';
    const file = options.file;

    if (!file || !fs.existsSync(file)) {
      throw new Error(`Restore SQL file not found: ${file}`);
    }

    try {
      let env = { ...process.env, PGPASSWORD: pass };
      let cmd = `psql -h ${host} -p ${port} -U ${user} -d ${db} -f "${file}"`;

      await execAsync(cmd, { env });
      return true;
    } catch (err) {
      // Driver fallback
      const client = new Client({ host, port, user, password: pass, database: db });
      await client.connect();
      const sql = fs.readFileSync(file, 'utf8');
      await client.query(sql);
      await client.end();
      return true;
    }
  }
}
